export const PLANES = {
  trial: {
    nombre: 'Prueba gratuita',
    precio: 0,
    maxStock: Infinity,
    maxVentasMes: Infinity,
    maxUsuarios: 3,
    duracionDias: 7,
    features: {
      catalogoPublico: true,
      reportesGanancia: true,
      valorStockTiempoReal: true,
      calculadoraPrecio: true,
      panelDeudores: true,
      resumenCobros: true,
      exportarExcel: true,
      botonWhatsappDeudores: true,
      reportesPorVendedor: true,
      dashboardGerencial: true,
      multiplesPointsVenta: true,
      historialEquipo: true,
      accesorios: true,
    },
  },
  basico: {
    nombre: 'Básico',
    precio: 7900,
    maxStock: 20,
    maxVentasMes: 10,
    maxUsuarios: 1,
    features: {
      catalogoPublico: false,
      reportesGanancia: false,
      valorStockTiempoReal: false,
      calculadoraPrecio: false,
      panelDeudores: false,
      resumenCobros: false,
      exportarExcel: false,
      botonWhatsappDeudores: false,
      reportesPorVendedor: false,
      dashboardGerencial: false,
      multiplesPointsVenta: false,
      historialEquipo: false,
    },
  },
  pro: {
    nombre: 'Pro',
    precio: 14900,
    maxStock: 60,
    maxVentasMes: 30,
    maxUsuarios: 3,
    features: {
      catalogoPublico: true,
      reportesGanancia: true,
      valorStockTiempoReal: true,
      calculadoraPrecio: true,
      panelDeudores: true,
      resumenCobros: true,
      exportarExcel: true,
      botonWhatsappDeudores: false,
      reportesPorVendedor: false,
      dashboardGerencial: false,
      multiplesPointsVenta: false,
      historialEquipo: false,
    },
  },
  promax: {
    nombre: 'Pro Max',
    precio: 29900,
    maxStock: Infinity,
    maxVentasMes: Infinity,
    maxUsuarios: Infinity,
    features: {
      catalogoPublico: true,
      reportesGanancia: true,
      valorStockTiempoReal: true,
      calculadoraPrecio: true,
      panelDeudores: true,
      resumenCobros: true,
      exportarExcel: true,
      botonWhatsappDeudores: true,
      reportesPorVendedor: true,
      dashboardGerencial: true,
      multiplesPointsVenta: true,
      historialEquipo: true,
    },
  },
};

// Alias backward-compat: "agencia" → promax
PLANES.agencia = PLANES.promax;

